import type { Metadata } from "next";
import { Hind_Siliguri, Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from "./_Component/NavBar";
import SearchBar from "./_Component/searchBar";
import Footer from "./_Component/Footer";
import { CartProvider } from "./context/CartContext";

const OpenSans = Open_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Corner Store a Ecommerce Online Shopping Category...",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${hindSiliguri.variable} ${OpenSans.variable} antialiased`}>
          <CartProvider>
            <header>
              <SearchBar />
              <NavBar />
            </header>

            <main>
              <section>
                {children}
              </section>
            </main>

            <footer className="wrap-4 bg-[#172337] py-[4em]">
              <Footer />
            </footer>
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
