import { Metadata } from "next";
import SideBar from "@/app/_Component/SideBar";

export const metadata: Metadata = {
  title: "Event",
  description: "Generated by create next app",
};

const Events = () => {
    return (
        <div className="banner">
            <aside>
                <SideBar />
            </aside>

            <div className="slide_banner">

            </div>

        </div>
    );
}

export default Events;